### ISSUE TITLE
Cannot use npm install

### ISSUE THREAD

**Issue by Bedwizard69** [Daltonic/slack-clone#3]
PS E:\Homework\ProJect daTa\slack-clone-master Git Repo> cd slack-clone-master
PS E:\Homework\ProJect daTa\slack-clone-master Git Repo\slack-clone-master> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-html-parser@2.0.2
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16.3.0" from @emotion/core@10.1.1
npm ERR!   node_modules/@emotion/core
npm ERR!     @emotion/core@"^10.0.35" from the root project
npm ERR!   14 more (@material-ui/core, @material-ui/icons, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm ERR! node_modules/react-html-parser
npm ERR!   react-html-parser@"^2.0.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm ERR!   node_modules/react-html-parser
npm ERR!     react-html-parser@"^2.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\sonug\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sonug\AppData\Local\npm-cache\_logs\2022-11-27T18_10_45_360Z-debug-0.log
PS E:\Homework\ProJect daTa\slack-clone-master Git Repo\slack-clone-master>

**Comment by adambevil** [comment]
Same issue on my end

**Comment by anish-k2308** [comment]
how to resolve this issue
